#!/bin/bash

set -e -u

echo "\
SYNCER_MBOX_GUID=$SYNCER_MBOX_GUID \
SYNCER_MODE_TYPE=$SYNCER_MODE_TYPE \
SYNCER_MBOX_NAME=$SYNCER_MBOX_NAME \
SYNCER_MBOX_PATH=$SYNCER_MBOX_PATH \
SYNCER_USER_NAME=$SYNCER_USER_NAME \
SYNCER_MAIL_HOME=$SYNCER_MAIL_HOME \
"
